// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers method parameter property variants:
    ///  - optional parameter `x?: T`
    ///  - default-value parameter `x: T = ...`
    ///  - rest parameter `...xs: T[]`
    /// </summary>
    public class ParameterProperties
    {
        public double Maybe(double? x = default)
        {
            return x ?? 0;
        }
        
        
        public double Defaulted(double x = 10)
        {
            return x;
        }
        
        
        public double Rest(params double[] xs)
        {
            double total = 0;
            foreach (double x in xs)
            {
                total += x;
            }
            return total;
        }
        
        
    }
    
}
