// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public static class InputGlobals
    {
        /// <summary>
        /// Top-level async generic function. Verifies the wrapper's static method
        /// picks up both the async-rewrite pass and type-parameter handling.
        /// </summary>
        public static async System.Threading.Tasks.Task<T> Identity<T>(T value)
        {
            return value;
        }
        
        
    }
    
}
