// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers abstract class declarations:
 *  - abstract class with abstract methods (no body)
 *  - abstract class with a concrete method
 *  - concrete subclass that extends the abstract class
 *  - override keyword on implemented abstract methods
 *  - calling a concrete method defined on the abstract base
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public abstract class Shape
{
    public abstract fun area(): Double
    
    public abstract fun perimeter(): Double
    
    public fun describe(): String{
        return """area=${(this.area()).toTemplate()}, perimeter=${(this.perimeter()).toTemplate()}"""
    }
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Circle: alphaTab.Shape
{
    private var radius: Double
    
    public constructor(radius: Double)
        : super(){
        this.radius = radius
    }
    
    public override fun area(): Double{
        return (3.14159).toDouble() * this.radius * this.radius
    }
    
    public override fun perimeter(): Double{
        return (2.0).toDouble() * (3.14159).toDouble() * this.radius
    }
    
}

