// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers `||=` and `&amp;&amp;=` on boolean operands.
    /// These lower to `f = f || rhs` / `f = f &amp;&amp; rhs` without int-casts.
    /// </summary>
    public class LogicalAssignBool
    {
        public bool OrAssign(bool a, bool b)
        {
            bool f = a;
            f = f || b;
            return f;
        }
        
        
        public bool AndAssign(bool a, bool b)
        {
            bool f = a;
            f = f && b;
            return f;
        }
        
        
    }
    
}
