// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    [AlphaTab.Test.TestClass("MyTests")]
    public class MyTests
    {
        [AlphaTab.Test.TestMethod("should add")]
        public void ShouldAdd()
        {
            double a = 1;
            double b = 2;
            double c = a + b;
            if (c != 3)
            {
                throw new Error("fail");
            }
        }
        
        
        [AlphaTab.Test.TestMethod("should subtract")]
        public void ShouldSubtract()
        {
            double a = 5;
            double b = 2;
            double c = a - b;
            if (c != 3)
            {
                throw new Error("fail");
            }
        }
        
        
    }
    
}
