// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public interface Printable
    {
        string Print();
        
        
    }
    
    public interface Container<T>
    {
        T Get();
        
        
        void Set(T value);
        
        
    }
    
    public class PrintableBox<T>: AlphaTab.Container<T>
        where T : AlphaTab.Printable
    {
        private T _value;
        
        public PrintableBox(T value)
        {
            this._value = value;
        }
        
        public T Get()
        {
            return this._value;
        }
        
        
        public void Set(T value)
        {
            this._value = value;
        }
        
        
        public string PrintValue()
        {
            return this._value.Print();
        }
        
        
    }
    
}
