// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Minimal disposable resource for the `using` fixture. We avoid declaring
 * `implements Disposable` because the transpiler does not currently
 * support Symbol.dispose computed method names; the `dispose()` method
 * below is what the emitter understands.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Resource
{
    public fun dispose(): Unit{
    }
    
    public constructor()
}

/**
 * Minimal async-disposable resource for the `await using` fixture.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class AsyncResource
{
    public suspend fun disposeAsync(): Unit{
    }
    
    public constructor()
}

/**
 * Covers `using` and `await using` declarations introduced by ECMAScript
 * explicit resource management.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class UsingExample
{
    public fun doStuff(): Unit{
        var r: Disposable = ((alphaTab.Resource() as Any?) as Disposable)
        r.use {
        }
    }
    
    public suspend fun doStuffAsync(): Unit{
        var r: alphaTab.core.ecmaScript.AsyncDisposable = ((alphaTab.AsyncResource() as Any?) as alphaTab.core.ecmaScript.AsyncDisposable)
    }
    
    public constructor()
}

