// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class Collections
    {
        public System.Collections.Generic.IList<double> MakeList()
        {
            return new AlphaTab.Collections.List<double>{
                1, 2, 3}
            ;
        }
        
        
        public double Get(System.Collections.Generic.IList<double> items, double index)
        {
            return items[(int)(index)];
        }
        
        
        public void Set(System.Collections.Generic.IList<double> items, double index, double value)
        {
            items[(int)(index)] = value;
        }
        
        
        public AlphaTab.Collections.IValueTypeMap<string, double> MakeMap()
        {
            AlphaTab.Collections.IValueTypeMap<string, double> m = new AlphaTab.Collections.ValueTypeMap<string, double>();
            m.Set("a", 1);
            m.Set("b", 2);
            return m;
        }
        
        
        public double Lookup(AlphaTab.Collections.IValueTypeMap<string, double> m, string key)
        {
            return m.Get(key) ?? 0;
        }
        
        
    }
    
}
