// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class BreakContinue
    {
        public double FirstNegative(System.Collections.Generic.IList<double> items)
        {
            foreach (double item in items)
            {
                if (item < 0)
                {
                    return item;
                }
            }
            return 0;
        }
        
        
        public double SumPositive(System.Collections.Generic.IList<double> items)
        {
            double sum = 0;
            foreach (double item in items)
            {
                if (item <= 0)
                {
                    continue;
                }
                sum += item;
            }
            return sum;
        }
        
        
        public double FindFirst(System.Collections.Generic.IList<double> items, double target)
        {
            double idx = -1;
            for (double i = 0;i < items.Count;i++)
            {
                if (items[(int)(i)] == target)
                {
                    idx = i;
                    break;
                }
            }
            return idx;
        }
        
        
    }
    
}
