// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class BreakContinue
{
    /**
     */
    public fun firstNegative(items: alphaTab.collections.DoubleList): Double{
        for (item in items)
        {
            if (item < 0)
            {
                return item
            }
        }
        return 0.0
    }
    
    /**
     */
    public fun sumPositive(items: alphaTab.collections.DoubleList): Double{
        var sum: Double = 0.0
        for (item in items)
        {
            if (item <= 0)
            {
                continue
            }
            sum += item
        }
        return sum
    }
    
    /**
     */
    public fun findFirst(items: alphaTab.collections.DoubleList, target: Double): Double{
        var idx: Double = -1.0
        if (true) {
            var i: Double = 0.0
            
            while(i < items.length){
                if (items[(i).toInt()] == target)
                {
                    idx = i
                    break
                }
                i++
            }
        }
        return idx
    }
    
    public constructor()
}

