// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers control-flow statements:
    ///  - if/else
    ///  - for loop
    ///  - while loop
    ///  - switch with case and default
    /// </summary>
    public class ControlFlow
    {
        public string Classify(double n)
        {
            if (n < 0)
            {
                return "negative";
            }
            else if (n == 0)
            {
                return "zero";
            }
            else 
            {
                return "positive";
            }
        }
        
        
        public double Sum(double n)
        {
            double total = 0;
            for (double i = 0;i < n;i++)
            {
                total += i;
            }
            return total;
        }
        
        
        public double CountDown(double start)
        {
            double n = start;
            while (n > 0)
            {
                n--;
            }
            return n;
        }
        
        
        public string DayName(double day)
        {
            switch (day)
            {
                case 0:
                    return "Sunday";
                case 1:
                    return "Monday";
                case 6:
                    return "Saturday";
                default:
                    return "Weekday";
            }
        }
        
        
    }
    
}
