// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers control-flow statements:
 *  - if/else
 *  - for loop
 *  - while loop
 *  - switch with case and default
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ControlFlow
{
    /**
     */
    public fun classify(n: Double): String{
        if (n < 0)
        {
            return "negative"
        }
        else if (n == 0.0)
        {
            return "zero"
        }
        else 
        {
            return "positive"
        }
    }
    
    /**
     */
    public fun sum(n: Double): Double{
        var total: Double = 0.0
        if (true) {
            var i: Double = 0.0
            
            while(i < n){
                total += i
                i++
            }
        }
        return total
    }
    
    /**
     */
    public fun countDown(start: Double): Double{
        var n: Double = start
        while (n > 0)
        {
            n--
        }
        return n
    }
    
    /**
     */
    public fun dayName(day: Double): String{
        when (day)
        {
            0.0 -> 
            {
                return "Sunday"
            }
            1.0 -> 
            {
                return "Monday"
            }
            6.0 -> 
            {
                return "Saturday"
            }
            else -> 
            {
                return "Weekday"
            }
        }
    }
    
    public constructor()
}

