// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers enum declarations:
    ///  - numeric enum with default (auto-incremented) values
    ///  - numeric enum with explicit values
    ///  - numeric enum with negative literal value (exercises prefix-unary
    ///    enum smart-cast path)
    ///  - numeric enum with computed initializer (bitwise constant expression)
    ///  - using an enum value in an expression
    /// </summary>
    public enum Direction
    {
        Up,
        Down,
        Left,
        Right,
    }
    
    public enum Color
    {
        Red = 1,
        Green = 2,
        Blue = 4,
    }
    
    public enum Flags
    {
        None = 0,
        Read = (1 << 0),
        Write = (1 << 1),
        Execute = (1 << 2),
        All = (Read | Write | (int)(Execute)),
    }
    
    public enum Signed
    {
        Off = -1,
        On = 1,
    }
    
    public class Palette
    {
        public AlphaTab.Direction GetDirection()
        {
            return AlphaTab.Direction.Up;
        }
        
        
        public double MixColor(AlphaTab.Color c)
        {
            return c | AlphaTab.Color.Green;
        }
        
        
        public AlphaTab.Flags ToggleFlag(AlphaTab.Flags f)
        {
            return f ^ AlphaTab.Flags.Read;
        }
        
        
        public AlphaTab.Signed DefaultSign()
        {
            return AlphaTab.Signed.Off;
        }
        
        
    }
    
}
