// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public static class InputGlobals
    {
        /// <summary>
        /// Top-level function with overload signatures plus one implementation.
        /// Only the implementation should land in the wrapper; the signatures are
        /// skipped silently.
        /// </summary>
        public static string Describe(object x)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"value: {0}", (x).ToTemplate());
        }
        
        
    }
    
}
