// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Direction enum used to exercise bracket access against numeric and
    /// string keys.
    /// </summary>
    public enum Direction
    {
        Up,
        Down,
        Left,
        Right,
    }
    
    /// <summary>
    /// Covers TypeScript's reverse-mapping bracket access on numeric enums:
    ///  - Direction[d]   numeric value to member name
    ///  - Direction[s]   member name to numeric value (via keyof typeof)
    /// </summary>
    public class EnumBracketAccess
    {
        public string Name(AlphaTab.Direction d)
        {
            return d.ToString();
        }
        
        
        public AlphaTab.Direction Parse(string s)
        {
            return AlphaTab.Core.TypeHelper.ParseEnum<AlphaTab.Direction>((string)s, typeof(AlphaTab.Direction));
        }
        
        
    }
    
}
