// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Direction enum used to exercise bracket access against numeric and
 * string keys.
 */
public enum class Direction(override val value: Int): alphaTab.core.IAlphaTabEnum
{
    Up(0),
    Down(1),
    Left(2),
    Right(3);
    companion object : alphaTab.core.IAlphaTabEnumCompanion<Direction>{
        public override val values = arrayOf(Up, Down, Left, Right) 
        public override fun fromValue(v:Double): Direction{
            return when(v.toInt()){
                Up.value -> Up
                Down.value -> Down
                Left.value -> Left
                Right.value -> Right
                else -> throw ClassCastException("No enum with value $v found")}
        }
    }
}

/**
 * Covers TypeScript's reverse-mapping bracket access on numeric enums:
 *  - Direction[d]   numeric value to member name
 *  - Direction[s]   member name to numeric value (via keyof typeof)
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class EnumBracketAccess
{
    /**
     */
    public fun name(d: alphaTab.Direction): String{
        return d.toString()
    }
    
    /**
     */
    public fun parse(s: String): alphaTab.Direction{
        return alphaTab.core.TypeHelper.parseEnum<alphaTab.Direction>(s.toString(), alphaTab.Direction::class)
    }
    
    public constructor()
}

