// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class UnknownCast
    {
        public double Coerce(object? value)
        {
            return AlphaTab.Core.TypeHelper.UnknownToNumber(value);
        }
        
        
        public double CoerceWithDefault(object? value)
        {
            double n = AlphaTab.Core.TypeHelper.UnknownToNumber(value);
            return n + 1;
        }
        
        
    }
    
}
