// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers Number(s: string) -&gt; double.Parse(s, InvariantCulture) in C#
    /// and s.toDouble() in Kotlin.
    /// </summary>
    public class NumberFromString
    {
        public double ToNum(string s)
        {
            return Double.Parse(s, System.Globalization.CultureInfo.InvariantCulture);
        }
        
        
    }
    
}
