// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Old shape API kept around for backwards compatibility.
    /// </summary>
    [System.ObsoleteAttribute("Use NewShape instead.")]
    public class OldShape
    {
        /// <summary>
        /// Legacy area calculation entry point.
        /// </summary>
        [System.ObsoleteAttribute("use area() instead")]
        public double Calc()
        {
            return 0;
        }
        
        
        public double Area()
        {
            return 0;
        }
        
        
    }
    
}
