// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers static accessor emission:
 *  - static getter (lazy singleton pattern)
 *  - static getter / setter pair
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Singleton
{
    companion object{
        @kotlin.jvm.JvmStatic
        private var _instance: alphaTab.Singleton? = null
        
        @kotlin.jvm.JvmStatic
        private var _version: Double = 1.0
        
        @kotlin.jvm.JvmStatic
        public val instance: alphaTab.Singleton
        get(){
            if (alphaTab.Singleton._instance == null)
            {
                alphaTab.Singleton._instance = alphaTab.Singleton()
            }
            return alphaTab.Singleton._instance!!
        }
        
        @kotlin.jvm.JvmStatic
        public var version: Double
        get(){
            return alphaTab.Singleton._version
        }
        set(value){
            alphaTab.Singleton._version = v
        }
        
    }
    public constructor()
}

