// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers static accessor emission:
    ///  - static getter (lazy singleton pattern)
    ///  - static getter / setter pair
    /// </summary>
    public class Singleton
    {
        private static AlphaTab.Singleton? _instance = null;
        
        private static double _version = 1;
        
        public static AlphaTab.Singleton Instance
        {
            get
            {
                if (AlphaTab.Singleton._instance == null)
                {
                    AlphaTab.Singleton._instance = new AlphaTab.Singleton();
                }
                return AlphaTab.Singleton._instance!;
            }
        }
        
        public static double Version
        {
            get
            {
                return AlphaTab.Singleton._version;
            }
            set
            {
                var v = value;
                AlphaTab.Singleton._version = v;
            }
        }
        
    }
    
}
