// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers `new Promise&lt;T&gt;(resolve =&gt; ...)` construction, exercising the
    /// transpiler's lowering of explicit Promise instantiation.
    /// </summary>
    public class PromiseConstruction
    {
        public System.Threading.Tasks.Task<double> Delayed(double value)
        {
            return AlphaTab.Core.TypeHelper.CreatePromise<double>((System.Action<object> resolve) => {
                resolve(value);
            }
            );
        }
        
        
    }
    
}
