// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// A discriminated union for shape commands.
    /// </summary>
    public interface ShapeCommand
    {
        public string Kind
        {
            get;
            set;
        }
        
    }
    
    public class ShapeCommandCircle: ShapeCommand
    {
        public string Kind
        {
            get;
            set;
        }
         = "shape.circle";
        
        public double Radius
        {
            get;
            set;
        }
        
    }
    
    public class ShapeCommandRect: ShapeCommand
    {
        public string Kind
        {
            get;
            set;
        }
         = "shape.rect";
        
        public double Width
        {
            get;
            set;
        }
        
        public double Height
        {
            get;
            set;
        }
        
    }
    
    public class ShapeCommandPoint: ShapeCommand
    {
        public string Kind
        {
            get;
            set;
        }
         = "shape.point";
        
    }
    
    public class ShapeProcessor
    {
        public string Describe(AlphaTab.ShapeCommand cmd)
        {
            switch (cmd.Kind)
            {
                case "shape.circle":
                    return "circle";
                case "shape.rect":
                    return "rect";
                default:
                    return "point";
            }
        }
        
        
        public AlphaTab.ShapeCommand MakeCircle()
        {
            return new AlphaTab.ShapeCommandCircle()
            {
                Kind = "shape.circle",
                Radius = 5,
            }
            ;
        }
        
        
        public AlphaTab.ShapeCommand MakeRect()
        {
            return new AlphaTab.ShapeCommandRect()
            {
                Kind = "shape.rect",
                Width = 10,
                Height = 20,
            }
            ;
        }
        
        
        public AlphaTab.ShapeCommand MakePoint()
        {
            return new AlphaTab.ShapeCommandPoint()
            {
                Kind = "shape.point",
            }
            ;
        }
        
        
    }
    
}
