// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * A discriminated union for shape commands.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public interface ShapeCommand
{
    public var kind: String
    
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ShapeCommandCircle: ShapeCommand
{
    public override var kind: String = "shape.circle"
    
    
    public var radius: Double = 0.0
    
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ShapeCommandRect: ShapeCommand
{
    public override var kind: String = "shape.rect"
    
    
    public var width: Double = 0.0
    
    
    public var height: Double = 0.0
    
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ShapeCommandPoint: ShapeCommand
{
    public override var kind: String = "shape.point"
    
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ShapeProcessor
{
    /**
     */
    public fun describe(cmd: alphaTab.ShapeCommand): String{
        when (cmd.kind)
        {
            "shape.circle" -> 
            {
                return "circle"
            }
            "shape.rect" -> 
            {
                return "rect"
            }
            else -> 
            {
                return "point"
            }
        }
    }
    
    public fun makeCircle(): alphaTab.ShapeCommand{
        return alphaTab.ShapeCommandCircle().apply {
            this.kind = "shape.circle"
            this.radius = 5.0
        }
        
    }
    
    public fun makeRect(): alphaTab.ShapeCommand{
        return alphaTab.ShapeCommandRect().apply {
            this.kind = "shape.rect"
            this.width = 10.0
            this.height = 20.0
        }
        
    }
    
    public fun makePoint(): alphaTab.ShapeCommand{
        return alphaTab.ShapeCommandPoint().apply {
            this.kind = "shape.point"
        }
        
    }
    
    public constructor()
}

