name: 🕷️ Bug Report
description: Report a bug.
labels: "state-needs-triage"
assignees: Danielku15
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  id: current
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. 
      2. 
      3. 
      4. 
  validations:
    required: true
- type: input
  id: link
  attributes:
    label: Link to jsFiddle, CodePen, Project
    description: Providing a minimal reproducible example can help a lot.
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Found in Version
    description: Which version of alphaTab are you using?
    options:
    - 1.3-alpha
    - 1.2
    - 1.1
    - 1.0
    - Other
  validations:
    required: true
- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: On which platform are you using alphaTab?
    options:
    - Web        
    - Node.js
    - .net (WPF)
    - .net (WinForms)
    - .net (Other)
    - Android (WebView)
    - Android (Native)
    - iOS (WebView)
    - Other
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Windows 10 Pro
        - **Browser**: Chrome 92.0.4515.159
    value: |
      - **OS**:
      - **Browser**:
      - **.net Version**:
    render: markdown
  validations:
    required: true
- type: textarea
  id: further
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
