// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public interface Named
    {
        string Name
        {
            get;
        }
        
    }
    
    /// <summary>
    /// Covers an interface that extends another interface, plus a class
    /// implementing the derived interface.
    /// </summary>
    public interface Tagged: AlphaTab.Named
    {
        string Tag
        {
            get;
        }
        
    }
    
    public class Label: AlphaTab.Tagged
    {
        public string Name
        {
            get;
        }
         = "";
        
        public string Tag
        {
            get;
        }
         = "";
        
    }
    
}
