// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Class with a mix of public and
    /// </summary>
    public class Mixed
    {
        public double PublicField
        {
            get;
            set;
        }
         = 0;
        
        internal double InternalField
        {
            get;
            set;
        }
         = 0;
        
        public double PublicMethod()
        {
            return this.PublicField;
        }
        
        
        internal double InternalMethod()
        {
            return this.InternalField;
        }
        
        
    }
    
}
