// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Default-exported class alongside top-level helpers. Both should emit
    /// side-by-side: the class as itself, the helpers inside `InputGlobals`.
    /// </summary>
    public class Calculator
    {
        public double Add(double a, double b)
        {
            return InputGlobals.Clamp(a + b);
        }
        
        
    }
    
    public static class InputGlobals
    {
        public static double Clamp(double n)
        {
            if (n < 0)
            {
                return 0;
            }
            return n;
        }
        
        
    }
    
}
