// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers generic class and method declarations:
 *  - generic class with unconstrained type parameter T
 *  - generic class with constrained type parameter T extends SomeBase
 *  - generic static method on a non-generic class
 *  - instantiating a generic class
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Box<T>
{
    private var value: T
    
    public constructor(value: T){
        this.value = value
    }
    
    public fun get(): T{
        return this.value
    }
    
    /**
     */
    public fun set(value: T): Unit{
        this.value = value
    }
    
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Comparable
{
    public var score: Double = 0.0
    
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class MinBox<T>
    where T : alphaTab.Comparable
{
    private var items: alphaTab.collections.List<T> = alphaTab.collections.List<T>(
    )
    
    
    /**
     */
    public fun add(item: T): Unit{
        this.items.push(item)
    }
    
    public fun min(): T?{
        if (this.items.length == 0.0)
        {
            return null
        }
        var best: T = this.items[(0).toInt()]
        for (item in this.items)
        {
            if (item.score < best.score)
            {
                best = item
            }
        }
        return best
    }
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Utils
{
    companion object{
        /**
         */
        @kotlin.jvm.JvmStatic
        public fun <T>identity(value: T): T{
            return value
        }
        
    }
    public constructor()
}

