// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers generic class and method declarations:
    ///  - generic class with unconstrained type parameter T
    ///  - generic class with constrained type parameter T extends SomeBase
    ///  - generic static method on a non-generic class
    ///  - instantiating a generic class
    /// </summary>
    public class Box<T>
    {
        private T Value;
        
        public Box(T value)
        {
            this.Value = value;
        }
        
        public T Get()
        {
            return this.Value;
        }
        
        
        public void Set(T value)
        {
            this.Value = value;
        }
        
        
    }
    
    public class Comparable
    {
        public double Score
        {
            get;
            set;
        }
         = 0;
        
    }
    
    public class MinBox<T>
        where T : AlphaTab.Comparable
    {
        private System.Collections.Generic.IList<T> Items = new AlphaTab.Collections.List<T>()
        ;
        
        public void Add(T item)
        {
            this.Items.Add(item);
        }
        
        
        public T? Min()
        {
            if (this.Items.Count == 0)
            {
                return null;
            }
            T best = this.Items[(int)(0)];
            foreach (T item in this.Items)
            {
                if (item.Score < best.Score)
                {
                    best = item;
                }
            }
            return best;
        }
        
        
    }
    
    public class Utils
    {
        public static T Identity<T>(T value)
        {
            return value;
        }
        
        
    }
    
}
