// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers interfaces and implements:
    ///  - interface with method and property signatures
    ///  - class that implements the interface
    /// </summary>
    public interface Shape
    {
        string Name
        {
            get;
        }
        
        double Area();
        
        
        double Perimeter();
        
        
    }
    
    public class Rectangle: AlphaTab.Shape
    {
        public string Name
        {
            get;
        }
         = "Rectangle";
        
        private double Width;
        
        private double Height;
        
        public Rectangle(double width, double height)
        {
            this.Width = width;
            this.Height = height;
        }
        
        public double Area()
        {
            return this.Width * this.Height;
        }
        
        
        public double Perimeter()
        {
            return (double)(2) * (this.Width + this.Height);
        }
        
        
    }
    
}
