// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers exception-handling statements:
 *  - throw new Error(...)
 *  - try/catch block
 *  - try/finally block
 *  - combined try/catch/finally in a single method
 *  - bare catch (no binding variable)
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class ExceptionHandling
{
    /**
     */
    public fun divide(a: Double, b: Double): Double{
        if (b == 0.0)
        {
            throw kotlin.Throwable("Division by zero")
        }
        return a / b
    }
    
    /**
     */
    public fun safeDouble(n: Double): Double{
        try
        {
            if (n < 0)
            {
                throw kotlin.Throwable("Negative input")
            }
            return n * (2.0).toDouble()
        }
        catch (e: kotlin.Throwable)
        {
            return 0.0
        }
    }
    
    /**
     */
    public fun withCleanup(value: Double): Double{
        var result: Double = 0.0
        try
        {
            result = value * (2.0).toDouble()
        }
        finally
        {
            result += 1.0
        }
        return result
    }
    
    /**
     */
    public fun fullCleanup(value: Double): Double{
        var result: Double = 0.0
        try
        {
            if (value < 0)
            {
                throw kotlin.Throwable("bad input")
            }
            result = value * (2.0).toDouble()
        }
        catch (e: kotlin.Throwable)
        {
            result = -1.0
        }
        finally
        {
            result += 1.0
        }
        return result
    }
    
    public fun bareCatch(): Double{
        try
        {
            throw kotlin.Throwable("oops")
        }
        catch (_e0: kotlin.Throwable){
            return -1.0
        }
    }
    
    public constructor()
}

