// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class NoSubstitution
    {
        public string Greeting()
        {
            return "Hello, World!";
        }
        
        
        public string Multiline()
        {
            return "line 1\nline 2";
        }
        
        
    }
    
}
