// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers TS built-in types whose mapping lives in the typeRegistry:
    /// Promise -&gt; Task / Deferred, Map -&gt; IMap, Array&lt;T&gt; -&gt; IList&lt;T&gt;,
    /// Iterable -&gt; IEnumerable. Set is excluded here because it would
    /// require runtime Set support which differs per target.
    /// </summary>
    public class Builtins
    {
        public System.Collections.Generic.IList<double> List
        {
            get;
            set;
        }
         = new AlphaTab.Collections.List<double>()
        ;
        
        public AlphaTab.Collections.IValueTypeMap<string, double> Lookup
        {
            get;
            set;
        }
         = new AlphaTab.Collections.ValueTypeMap<string, double>();
        
        public System.Collections.Generic.IList<string> AsArray
        {
            get;
            set;
        }
         = new AlphaTab.Collections.List<string>()
        ;
        
        public System.Collections.Generic.IEnumerable<double> Iter()
        {
            return this.List;
        }
        
        
        public async System.Threading.Tasks.Task<double> FetchValue()
        {
            return 42;
        }
        
        
        public double Count()
        {
            return this.List.Count;
        }
        
        
    }
    
}
