// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers TS built-in types whose mapping lives in the typeRegistry:
 * Promise -> Task / Deferred, Map -> IMap, Array<T> -> IList<T>,
 * Iterable -> IEnumerable. Set is excluded here because it would
 * require runtime Set support which differs per target.
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Builtins
{
    public var list: alphaTab.collections.DoubleList = alphaTab.collections.DoubleList(
    )
    
    
    
    public var lookup: alphaTab.collections.ObjectDoubleMap<String> = alphaTab.collections.ObjectDoubleMap<String>()
    
    
    public var asArray: alphaTab.collections.List<String> = alphaTab.collections.List<String>(
    )
    
    
    
    public fun iter(): kotlin.collections.Iterable<Double>{
        return this.list
    }
    
    public suspend fun fetchValue(): Double{
        return 42.0
    }
    
    public fun count(): Double{
        return this.list.length
    }
    
    public constructor()
}

