// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public partial class Splittable
    {
        public string Name
        {
            get;
            set;
        }
         = "";
        
        public string Greet()
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"Hello, {0}", (this.Name).ToTemplate());
        }
        
        
    }
    
}
