// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers static member declarations:
    ///  - static property with initializer
    ///  - static readonly property
    ///  - static method
    ///  - accessing static property from a static method via ClassName.field
    ///  - accessing static property from an instance method via ClassName.field
    /// </summary>
    public class Counter
    {
        private static double Count = 0;
        
        public const double MaxCount = 100;
        
        public static void Increment()
        {
            AlphaTab.Counter.Count++;
        }
        
        
        public static double GetCount()
        {
            return AlphaTab.Counter.Count;
        }
        
        
        public bool IsAtMax()
        {
            return AlphaTab.Counter.Count >= AlphaTab.Counter.MaxCount;
        }
        
        
    }
    
}
