// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Inner type used by the optional-chaining test below. Kept as a named
    /// class because the transformer rejects anonymous object-literal types.
    /// </summary>
    public class Inner
    {
        public double Value
        {
            get;
            set;
        }
         = 0;
        
    }
    
    /// <summary>
    /// Wrapping container so the chain has a real `.inner?` step. The wrapper
    /// holds an optional Inner; both the wrapper and Inner.value participate
    /// in the optional-chaining expression.
    /// </summary>
    public class Wrapper
    {
        public AlphaTab.Inner? Inner
        {
            get;
            set;
        }
         = null;
        
    }
    
    /// <summary>
    /// Covers nullable-via-union (`T | null`, `T | undefined`),
    /// non-null assertion (`!`), nullish coalescing (`??`),
    /// and optional chaining (`?.`).
    /// </summary>
    public class NullableAndUnion
    {
        public string? Optional
        {
            get;
            set;
        }
         = null;
        
        public string? Undef
        {
            get;
            set;
        }
         = null;
        
        public string Choice
        {
            get;
            set;
        }
         = "a";
        
        public string Defaulted(string? s)
        {
            return s ?? "fallback";
        }
        
        
        public double Bang(string? s)
        {
            return s!.Length;
        }
        
        
        public double Chain(AlphaTab.Wrapper? o)
        {
            return o?.Inner?.Value ?? -1;
        }
        
        
    }
    
}
