// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers tuple destructure ASSIGNMENT (not declaration).
    /// `[a, b] = [b, a]` should reassign both locals.
    /// </summary>
    public class TupleDeconstruct
    {
        public AlphaTab.Core.ArrayTuple<double, double> Swap()
        {
            double a = 1;
            double b = 2;
            (a, b) = new AlphaTab.Core.ArrayTuple<double, double>(b, a);
            return new AlphaTab.Core.ArrayTuple<double, double>(a, b);
        }
        
        
    }
    
}
