// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Constructor parameter properties (TS shorthand). Each modifier flavour
    /// produces a property + an injected `this.X = x` assignment in the body.
    /// A plain parameter (no modifier) stays a parameter only.
    /// </summary>
    public class Point
    {
        public double X
        {
            get;
        }
        
        public double Y
        {
            get;
        }
        
        private string Kind;
        
        public Point(double x, double y, string label, string kind = "cartesian")
        {
            this.X = x;
            this.Y = y;
            this.Kind = kind;
            this.Kind = string.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0}:{1}", (this.Kind).ToTemplate(), (label).ToTemplate());
        }
        
        public string Summary()
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0}({1},{2})", (this.Kind).ToTemplate(), (this.X).ToTemplate(), (this.Y).ToTemplate());
        }
        
        
    }
    
}
