// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class ForNestedContinue
    {
        public double Baseline(System.Collections.Generic.IList<double> items)
        {
            double sum = 0;
            for (double i = 0;i < items.Count;i++)
            {
                if (items[(int)(i)] < 0)
                {
                    continue;
                }
                sum += items[(int)(i)];
            }
            return sum;
        }
        
        
        public double NestedForOf(System.Collections.Generic.IList<double> outer, System.Collections.Generic.IList<double> inner)
        {
            double sum = 0;
            for (double i = 0;i < outer.Count;i++)
            {
                foreach (double v in inner)
                {
                    if (v < 0)
                    {
                        continue;
                    }
                    sum += outer[(int)(i)] + v;
                }
            }
            return sum;
        }
        
        
        public double NestedWhile(System.Collections.Generic.IList<double> outer, double target)
        {
            double sum = 0;
            for (double i = 0;i < outer.Count;i++)
            {
                double j = 0;
                while (j < outer.Count)
                {
                    j++;
                    if (outer[(int)(j - (double)(1))] == target)
                    {
                        continue;
                    }
                    sum += outer[(int)(j - (double)(1))];
                }
            }
            return sum;
        }
        
        
        public double NestedDoWhile(System.Collections.Generic.IList<double> outer)
        {
            double sum = 0;
            for (double i = 0;i < outer.Count;i++)
            {
                double j = 0;
                do
                {
                    j++;
                    if (outer[(int)(j - (double)(1))] < 0)
                    {
                        continue;
                    }
                    sum += outer[(int)(j - (double)(1))];
                }
                while (j < outer.Count);
            }
            return sum;
        }
        
        
        public double NestedCStyle(System.Collections.Generic.IList<double> outer, System.Collections.Generic.IList<double> inner)
        {
            double sum = 0;
            for (double i = 0;i < outer.Count;i++)
            {
                for (double j = 0;j < inner.Count;j++)
                {
                    if (inner[(int)(j)] < 0)
                    {
                        continue;
                    }
                    sum += outer[(int)(i)] + inner[(int)(j)];
                }
            }
            return sum;
        }
        
        
        public double ContinueInSwitch(System.Collections.Generic.IList<double> items)
        {
            double sum = 0;
            for (double i = 0;i < items.Count;i++)
            {
                switch (items[(int)(i)])
                {
                    case 0:
                        continue;
                    default:
                        sum += items[(int)(i)];
                        break;
                }
            }
            return sum;
        }
        
        
        public double BreakInNested(System.Collections.Generic.IList<double> outer, double target)
        {
            for (double i = 0;i < outer.Count;i++)
            {
                foreach (double v in outer)
                {
                    if (v == target)
                    {
                        break;
                    }
                }
            }
            return -1;
        }
        
        
    }
    
}
