// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers generic delegate type aliases used as parameter types.
 * Exercises that type arguments are threaded through to the emitted
 * delegate reference (e.g. Predicate<T> -> Predicate<T>, not Predicate).
 */
@OptIn(kotlin.contracts.ExperimentalContracts::class)
@kotlin.ExperimentalUnsignedTypes
public typealias Predicate = (value: T) -> Boolean

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class GenericDelegate
{
    /**
     */
    public fun <T>check(value: T, pred: alphaTab.Predicate<T>): Boolean{
        return pred(value)
    }
    
    public constructor()
}

