// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Verifies that tuple-typed array destructuring still works correctly
    /// after the non-tuple lowering guard was added.
    /// </summary>
    public class ArrayDestructureTuple
    {
        public AlphaTab.Core.ArrayTuple<double, double> Swap(AlphaTab.Core.ArrayTuple<double, double> pair)
        {
            var (a, b) = ((AlphaTab.Core.ArrayTuple<object?, object?>)pair);
            return new AlphaTab.Core.ArrayTuple<double, double>(b, a);
        }
        
        
    }
    
}
