// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class Consumer
    {
        public double Run(double value)
        {
            return InputGlobals.Helper(value);
        }
        
        
    }
    
    public static class InputGlobals
    {
        /// <summary>
        /// Covers top-level functions: one
        /// </summary>
        public static double Helper(double x)
        {
            return x * (double)(2);
        }
        
        
        internal static double Combine(double a, double b)
        {
            return Helper(a) + Helper(b);
        }
        
        
    }
    
}
