// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Covers abstract property and abstract getter declarations:
 *  - abstract class with an abstract field
 *  - abstract class with an abstract getter
 *  - concrete subclass that overrides both
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public abstract class Shape
{
    public abstract var size: Double
    
    public abstract val label: String
    
    public fun describe(): String{
        return """${(this.label).toTemplate()}: ${(this.size).toTemplate()}"""
    }
    
    public constructor()
}

@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Square: alphaTab.Shape
{
    public override var size: Double = 0.0
    
    
    public constructor(size: Double)
        : super(){
        this.size = size
    }
    
    public override val label: String
    get(){
        return "square"
    }
    
}

