// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class DoWhile
    {
        public double SumTo(double n)
        {
            double sum = 0;
            double i = 0;
            do
            {
                sum += i;
                i++;
            }
            while (i <= n);
            return sum;
        }
        
        
        public double FirstPositive(double start)
        {
            double n = start;
            do
            {
                n++;
            }
            while (n <= 0);
            return n;
        }
        
        
    }
    
}
