// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers generator methods:
    ///  - method declared with leading * (generator)
    ///  - yield expression inside a generator
    ///  - Generator&lt;T&gt; return type
    ///  - empty generator with bare return
    /// </summary>
    public class Generators
    {
        public System.Collections.Generic.IEnumerator<double> Range(double n)
        {
            for (double i = 0;i < n;i++)
            {
                yield return i;
            }
        }
        
        
        public System.Collections.Generic.IEnumerator<double> Empty()
        {
            yield break;
        }
        
        
    }
    
}
