// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers class inheritance:
    ///  - extends keyword
    ///  - constructor with super() call
    ///  - method override with override keyword
    ///  - calling super.method()
    /// </summary>
    public class Animal
    {
        protected string Name
        {
            get;
            set;
        }
        
        public Animal(string name)
        {
            this.Name = name;
        }
        
        public virtual string Speak()
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0} makes a sound.", (this.Name).ToTemplate());
        }
        
        
    }
    
    public class Dog: AlphaTab.Animal
    {
        public Dog(string name)
            : base (name)
        {
        }
        
        public override string Speak()
        {
            string @base = base.Speak();
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"{0} Woof!", (@base).ToTemplate());
        }
        
        
    }
    
}
