// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class AsyncTag
    {
        public System.Threading.Tasks.Task<double> Load()
        {
            return AlphaTab.Core.EcmaScript.Promise.Resolve(42);
        }
        
        
    }
    
}
