// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    public class TypedArrays
    {
        public AlphaTab.Core.EcmaScript.Uint8Array Bytes
        {
            get;
            set;
        }
         = new AlphaTab.Core.EcmaScript.Uint8Array(0);
        
        public AlphaTab.Core.EcmaScript.Float32Array Floats
        {
            get;
            set;
        }
         = new AlphaTab.Core.EcmaScript.Float32Array(0);
        
        public double ByteAt(double i)
        {
            return this.Bytes[(int)(i)];
        }
        
        
        public AlphaTab.Core.EcmaScript.Uint8Array MakeBuffer(double size)
        {
            return new AlphaTab.Core.EcmaScript.Uint8Array(size);
        }
        
        
    }
    
}
