// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    [AlphaTab.Test.TestClass("Helpers")]
    public class Helpers
    {
        private static System.Func<double, double> Helper = (double n) => n * (double)(2);
        
        [AlphaTab.Test.TestMethod("uses helper")]
        public void UsesHelper()
        {
            double result = Helper(5);
            if (result != 10)
            {
                throw new Error("fail");
            }
        }
        
        
    }
    
}
