// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers template literal strings:
    ///  - basic template literal with variable interpolation
    ///  - template literal with expression interpolation
    ///  - template literal with method call interpolation
    /// </summary>
    public class TemplateLiterals
    {
        public string Greet(string name)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"Hello, {0}!", (name).ToTemplate());
        }
        
        
        public string Describe(double x, double y)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"Point at ({0}, {1})", (x).ToTemplate(), (y).ToTemplate());
        }
        
        
        public string Summary(double items)
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, @"You have {0} item{1}.", (items).ToTemplate(), (items == 1 ? "" : "s").ToTemplate());
        }
        
        
    }
    
}
