// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

@file:Suppress(
    "KotlinRedundantDiagnosticSuppress",
    "RedundantVisibilityModifier",
    "RedundantExplicitType",
    "RedundantUnitReturnType",
    "RemoveRedundantQualifierName",
    "RemoveExplicitTypeArguments",
    "MemberVisibilityCanBePrivate",
    "MoveLambdaOutsideParentheses",
    "ConvertSecondaryConstructorToPrimary",
    "RemoveRedundantCallsOfConversionMethods",
    "MayBeConstant",
    "UnusedImport",
    "CanBeVal",
    "CascadeIf",
    "unused",
    "LocalVariableName",
    "NON_EXHAUSTIVE_WHEN",
    "UNCHECKED_CAST",
    "USELESS_CAST",
    "DEPRECATION",
    "PARAMETER_NAME_CHANGED_ON_OVERRIDE",
    "UNNECESSARY_NOT_NULL_ASSERTION",
    "UNNECESSARY_SAFE_CALL",
    "UNUSED_ANONYMOUS_PARAMETER",
    "UNUSED_PARAMETER",
    "UNUSED_VALUE",
    "UNREACHABLE_CODE",
    "REDUNDANT_ELSE_IN_WHEN",
    "VARIABLE_WITH_REDUNDANT_INITIALIZER"
)
package alphaTab
import alphaTab.core.*

/**
 * Exercises every operator family in CSharpAstTransformer.visitBinaryExpression:
 *  - integer bit ops (& | ^ << >> >>>) with their double-cast wrapping
 *  - compound bit-op assignment (>>=, &=, |=, ^=) and short-circuit assignment
 *    (??=) — the long bit-op decomposition block
 *  - real arithmetic (* / - %) with numeric-literal-to-double promotion
 *  - arithmetic compound assignment (-=, *=, /=, %=)
 *  - string+number concat in both directions (toInvariantString coercion)
 *  - `in` keyword -> TypeHelper.In
 *  - `instanceof` -> IsExpression
 */
@kotlin.contracts.ExperimentalContracts
@kotlin.ExperimentalUnsignedTypes
public class Binary
{
    /**
     */
    public fun bits(a: Double, b: Double): Double{
        return (((a).toInt() and 255) or ((b).toInt() shl 8)).toDouble()
    }
    
    /**
     */
    public fun shift(a: Double): Double{
        return ((a).toInt() shr 2).toDouble()
    }
    
    /**
     */
    public fun unsignedShift(a: Double): Double{
        return ((a).toInt() shr 1).toDouble()
    }
    
    /**
     */
    public fun mask(a: Double, m: Double): Double{
        var x: Double = a
        x = ((x.toInt()) and (m)).toDouble()
        x = ((x.toInt()) or (16)).toDouble()
        x = ((x.toInt()) xor (255)).toDouble()
        x = ((x.toInt()) shl (2)).toDouble()
        x = ((x.toInt()) shr (1)).toDouble()
        return x
    }
    
    /**
     */
    public fun arith(a: Double, b: Double): Double{
        return a * (2.0).toDouble() + b / (4.0).toDouble() - (3.0).toDouble()
    }
    
    /**
     */
    public fun concat(n: Double): String{
        return "value=" + (n).toInvariantString()
    }
    
    /**
     */
    public fun concatRev(n: Double): String{
        return (n).toInvariantString() + " items"
    }
    
    /**
     */
    public fun hasKey(o: Any?, k: String): Boolean{
        return alphaTab.core.TypeHelper.`in`(k, o)
    }
    
    /**
     */
    public fun isError(e: Any?): Boolean{
        return e is kotlin.Throwable
    }
    
    /**
     */
    public fun shortCircuit(a: Double?, b: Double?): Double{
        var x: Double? = a
        x = x?: 0.0
        var y: Double? = b
        y = y?: 1.0
        return x!! + y!!
    }
    
    /**
     */
    public fun arithAssign(a: Double): Double{
        var x: Double = a
        x -= 1.0
        x *= 2.0
        x /= 3.0
        x %= 5.0
        return x
    }
    
    /**
     */
    public fun mod(a: Double, b: Double): Double{
        return a % b
    }
    
    /**
     */
    public fun modAssign(a: Double, b: Double): Double{
        var x: Double = a
        x %= b
        return x % 7.0
    }
    
    public constructor()
}

