// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Covers `async` methods that `await` other promise-returning methods,
    /// pinning the transpiler's async/await lowering for both targets.
    /// </summary>
    public class AwaitExample
    {
        public async System.Threading.Tasks.Task<double> Load()
        {
            double value = await this.FetchValue();
            return value + 1;
        }
        
        
        public async System.Threading.Tasks.Task<double> FetchValue()
        {
            return 42;
        }
        
        
    }
    
}
