// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
#nullable enable annotations

using System;
using AlphaTab.Core;

namespace AlphaTab
{
    /// <summary>
    /// Tiny helper class used by the optional chaining fixture.
    /// </summary>
    public class Handler
    {
        public double Run()
        {
            return 0;
        }
        
        
    }
    
    /// <summary>
    /// Covers optional call chaining (`obj?.method()`) and optional element
    /// access (`arr?.[i]`), combined with the `??` fallback.
    /// </summary>
    public class OptionalCallChain
    {
        public double MaybeRun(AlphaTab.Handler? h)
        {
            return h?.Run() ?? -1;
        }
        
        
        public double MaybeLookup(System.Collections.Generic.IList<double>? items, double i)
        {
            return items?[(int)(i)] ?? -1;
        }
        
        
    }
    
}
