name: Nightly
on: 
  push:
    branches: 
      - develop
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nighty_web:
    name: Web
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/CoderLine
      - run: npm install
      - run: node ./scripts/update-version.js alpha ${{ github.run_number  }}
      - run: npm run build-ci
      - run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly_csharp:
    name: C#
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          source-url: https://nuget.pkg.github.com/CoderLine/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm install
      - run: npm run build-csharp-ci
      - run: dotnet nuget push ./src.csharp/AlphaTab/bin/Release/*.nupkg -k  $NUGET_AUTH_TOKEN
      - run: dotnet nuget push ./src.csharp/AlphaTab.Windows/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN
